[package]
name = "stealthnote_email_1024"
type = "bin"
authors = ["saleel"]
compiler_version = ">=1.0.0"
version = "0.3.1"

[dependencies]
zkemail = { tag = "v0.4.4", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
